set -g history-limit 500
set -g mouse on
set -g alternate-screen on
set -g detach-on-destroy off
#set -g renumber-windows on
set-option -g allow-rename off

#set -g pane-active-border-style fg=#0e1419
#set -g pane-border-style fg=#151b20
set -g status-style fg=#444556
set -g window-status-current-style fg=#434343,bold
set -g window-status-separator "   "

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g allow-passthrough on
set -sg escape-time 0
set -g focus-events on
set -s extended-keys always

set-option -g status-left-length 55
set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,} %H:%M %d-%b-%y"

setw -g mode-keys vi

bind-key -n C-z previous-window
bind-key -n C-x next-window

bind-key -n Ω previous-window
bind-key -n ≈ next-window

set-option -g prefix2 ∫
bind-key ∫ send-prefix -2
bind-key ˘ send-prefix -2

bind-key j new-session
bind-key h switch-client -p
bind-key k switch-client -n

bind-key "{" swap-window -d -t -1
bind-key "}" swap-window -d -t +1


if-shell 'test "$(uname)" = "Darwin"' \
    'set -g default-shell /opt/homebrew/bin/fish; set -g default-command "/opt/homebrew/bin/fish -l"' \
    'set -g default-shell /home/linuxbrew/.linuxbrew/bin/fish; set -g default-command "/home/linuxbrew/.linuxbrew/bin/fish -l"'
