# vim:set sw=4 ts=4 sts=4 et ft=fish fdm=marker fenc=utf-8:

# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 11

shell /opt/homebrew/bin/fish

repaint_delay 16
input_delay   2

scrollback_lines              2500
scrollback_pager_history_size 16

mouse_hide_wait    -1.0
copy_on_select     clipboard
macos_thicken_font 0.25

bell_on_tab          "🔔"
notify_on_cmd_finish unfocused 10
window_alert_on_bell yes

remember_window_size no
window_padding_width 4

disable_ligatures cursor
cursor_shape      block
shell_integration no-cursor

tab_bar_margin_width 32
tab_bar_style        separator
tab_separator        "  ⸱  "
# ⇥→⇒│❘‖␉▸⸱

tab_title_template        "{bell_symbol}{title[:12]} "
active_tab_title_template "{fmt.bold}{bell_symbol}{title[:12]}{fmt.nobold}★"
active_tab_font_style     bold
inactive_tab_font_style   normal

macos_quit_when_last_window_closed yes

hide_window_decorations titlebar-only

kitty_mod super+shift

map cmd+equal change_font_size all +1.0
map cmd+minus change_font_size all -1.0

map kitty_mod+[ previous_window
map kitty_mod+] next_window

map kitty_mod+f5 load_config_file

map cmd+q no_op
